# Prevent Jekyll from trying to parse Astro and Node project files
exclude:
  - "src/"
  - "node_modules/"
  - "package.json"
  - "package-lock.json"
  - "pnpm-lock.yaml"
  - "tsconfig.json"
  - "astro.config.*"
  - "dist/"
  - "public/"
  - "README.md"
  - "vite.config.*"
  - "pnpm-workspace.yaml"
